---
deployment: cf

jobs:
  - name: micro
    template:
      - postgres
  - name: micro_ng
    template:
      - nats
      - nats_stream_forwarder
      - cloud_controller_ng
      - cloud_controller_worker
      - cloud_controller_clock
      - uaa
      - haproxy
      - gorouter
      - dea_next
      - dea_logging_agent
      - loggregator
      - loggregator_trafficcontroller
      - etcd
      - hm9000

properties:
  networks:
    apps: default

  domain: 192.168.10.10.xip.io
  ssl:
    skip_cert_verify: true
  system_domain: 192.168.10.10.xip.io
  system_domain_organization: DevBox
  app_domains:
    - 192.168.10.10.xip.io

  disk_quota_enabled: true

  nats:
    user: nats
    password: c1oudc0w
    address: 192.168.10.10
    port: 4222
    machines:
      - 192.168.10.10

  dea_next: {}

  logger_endpoint:
    shared_secret: c1oudc0w

  cc: &cc
    bulk_api_password: c1oudc0w
    srv_api_uri: https://api.192.168.10.10.xip.io
    db_logging_level: debug2
    ccng.logging_level: debug2
    db_encryption_key: c1oudc0w
    quota_definitions:
      default:
        memory_limit: 10240
        total_services: 100
        non_basic_services_allowed: true
        total_routes: 1000
        trial_db_allowed: true
    hm9000_noop: false
    staging_upload_user: uploaduser
    staging_upload_password: c1oudc0w
    install_buildpacks:
      - name: java_buildpack
        package: buildpack_java
      - name: ruby_buildpack
        package: buildpack_ruby
      - name: nodejs_buildpack
        package: buildpack_nodejs
    security_group_definitions:
      - name: public_networks
        rules:
          - protocol: all
            destination: 0.0.0.0-9.255.255.255
          - protocol: all
            destination: 11.0.0.0-169.253.255.255
          - protocol: all
            destination: 169.255.0.0-172.15.255.255
          - protocol: all
            destination: 172.32.0.0-192.167.255.255
          - protocol: all
            destination: 192.169.0.0-255.255.255.255
      - name: private_networks
        rules:
          - protocol: all
            destination: 10.0.0.0-10.255.255.255
          - protocol: all
            destination: 172.16.0.0-172.31.255.255
          - protocol: all
            destination: 192.168.0.0-192.168.255.255
      - name: dns
        rules:
          - protocol: tcp
            destination: 0.0.0.0/0
            ports: '53'
          - protocol: udp
            destination: 0.0.0.0/0
            ports: '53'
    default_running_security_groups:
      - public_networks
      - private_networks
      - dns
    default_staging_security_groups:
      - public_networks
      - private_networks
      - dns
  ccng: *cc

  ccdb: &ccdb
    db_scheme: postgres
    address: 192.168.10.10
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: c1oudc0w
    databases:
      - tag: cc
        name: ccdb
        citext: true
  ccdb_ng: *ccdb

  uaadb:
    db_scheme: postgresql
    address: 192.168.10.10
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: c1oudc0w
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  databases:
    db_scheme: postgres
    address: 192.168.10.10
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: c1oudc0w
      - tag: admin
        name: uaaadmin
        password: c1oudc0w
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true
  db: databases

  uaa:
    login:
      addnew: false
    url: https://uaa.192.168.10.10.xip.io
    catalina_opts: -Xmx384m -XX:MaxPermSize=128m
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: c1oudc0w
    admin:
      client_secret: c1oudc0w
    batch:
      username: batch-username
      password: c1oudc0w
    clients: {}
    scim:
      users:
      - admin|c1oudc0w|scim.write,scim.read,openid,cloud_controller.admin

  etcd:
    machines:
      - 192.168.10.10

  router:
    port: 8888
    status:
      port: 18888
      user: gorouter
      password: c1oudc0w
    servers:
      z1:
        - 192.168.10.10
      z2: []

  login:
    enabled: false

  loggregator:
    zone: default
    status:
      user: loggregator
      password: c1oudc0w
      port: 5768
    incoming_port: 3456
    outgoing_port: 38080
    servers:
      default:
        - 192.168.10.10

  traffic_controller:
    zone: default
    status:
      user: trafic_controller
      password: c1oudc0w
      port: 6789
    incoming_port: 13456
    outgoing_port: 48080

  metron_endpoint: &metron_endpoint
    shared_secret: c1oudc0w
    host: 192.168.10.10
    port: 13456
  loggregator_endpoint: *metron_endpoint

  ha_proxy:
    ssl_pem: |
      -----BEGIN CERTIFICATE-----
      MIICtzCCAiACCQDoT66azx5GHzANBgkqhkiG9w0BAQUFADCBnzELMAkGA1UEBhMC
      SlAxDjAMBgNVBAgTBVRva3lvMREwDwYDVQQHEwhTaGluanVrdTETMBEGA1UEChMK
      QXJpZWx3b3JrczEgMB4GA1UECxMXVGhpcmQgRGV2ZWxvcG1lbnQgR3JvdXAxETAP
      BgNVBAMUCCoueGlwLmlvMSMwIQYJKoZIhvcNAQkBFhR5dWRhaUBhcmllbHdvcmtz
      LmNvbTAeFw0xNDA4MjkyMjI0MDVaFw0yNDA4MjYyMjI0MDVaMIGfMQswCQYDVQQG
      EwJKUDEOMAwGA1UECBMFVG9reW8xETAPBgNVBAcTCFNoaW5qdWt1MRMwEQYDVQQK
      EwpBcmllbHdvcmtzMSAwHgYDVQQLExdUaGlyZCBEZXZlbG9wbWVudCBHcm91cDER
      MA8GA1UEAxQIKi54aXAuaW8xIzAhBgkqhkiG9w0BCQEWFHl1ZGFpQGFyaWVsd29y
      a3MuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDThK53AAsPfUQ7vHUN
      LmmHHky/q7YD1O1h/mLObUW5XktF1HbMEKgQOIMUyVt6EPrfoeSiwq7HhYMwd4AT
      nmI/zEjQh7ob3B7cDIUEt1bWB5aCWCR9IZC/bUDdaTcUiEQKQNTwwCEFV8aby2yv
      PxAZUCX8xfJ9zbkkkyX5CIIlWQIDAQABMA0GCSqGSIb3DQEBBQUAA4GBAAglzdGZ
      9mrU8LlOzRl+2hZalV8lmECOsz7q8gkPavACxugCITLi/jkmEcieFq8mi8XmdJtq
      vI2fL04FVnCcwUIf0iHUa49hH2xjXG5zMNoVgn3BLRX/2z7XSMxJmQYvknrajmJo
      AbA/9cmQyh688dzFgyruGFIDCnmIZAp3valP
      -----END CERTIFICATE-----
      -----BEGIN RSA PRIVATE KEY-----
      MIICXQIBAAKBgQDThK53AAsPfUQ7vHUNLmmHHky/q7YD1O1h/mLObUW5XktF1HbM
      EKgQOIMUyVt6EPrfoeSiwq7HhYMwd4ATnmI/zEjQh7ob3B7cDIUEt1bWB5aCWCR9
      IZC/bUDdaTcUiEQKQNTwwCEFV8aby2yvPxAZUCX8xfJ9zbkkkyX5CIIlWQIDAQAB
      AoGBAMXCdcP5HF49BoC7cM0EKdIU+Dj0eFcYy2ElkIfkDp6DlOkS/odIw3l2/MeA
      g7CbE5PnL3clgng1UjUMZYjyOnQsIj0mB1r/+2+BlQawzI5wxf1+FsGoxSaggsRF
      3FvLxlOrW3zYRKEIvyQXIMaAB6m3RPTg+okm4Z6ZVwjyVR9JAkEA80Mkq34kE63x
      JCpR4UhvV49cRWAUs5OkrtrBgCiDvhWE6R6DUYjwhi53oNYdN/j4tryjMtioNbIn
      Nr8CGfRy/wJBAN6YBQzWpfCKDegCbPTXsrqr6vR1lE75/X/doxTQbJMfxmcu07FR
      dciHBDqcdn/9xs2B/8yKuN5hfqXeb6kh36cCQE6ZGCUM2a0+G1bbEZ+fntIEsQR9
      WdL31lLkvXaiIIbvPwVvZXCXtVc1dlOSOtiV6g5o/rX0CM1opYDr0EsAj5MCQHjm
      gPe0LnUzxtHZX2ytK3qQnhEhO+iZh8LHkyhe/Fn8zDqHCJwq7pp4Gyfqi8KBCFXe
      4h0qy7adpbhZ1LQ8nckCQQDvC9fMGRMFoiAMVB4IZ82Uo9LNSv77ontW5wx3QMAj
      vibyjG4OdVF3o8DLUGl734Ks+k+NA33V7+UebnWZSAtF
      -----END RSA PRIVATE KEY-----
